language: minimal
services: 
  - docker

script:
  - docker build -t udagram-api-feed:v1 ./udagram-api-feed
  - docker build -t udagram-api-user:v1 ./udagram-api-user
  - docker build -t udagram-frontend:latest ./udagram-frontend
  - docker build -t reverseproxy:latest ./udagram-reverseproxy
  - docker tag udagram-api-feed:v1 $DOCKER_USERNAME/udagram-api-feed
  - docker tag udagram-api-user:v1 $DOCKER_USERNAME/udagram-api-user
  - docker tag udagram-frontend:latest $DOCKER_USERNAME/udagram-frontend
  - docker tag reverseproxy:latest $DOCKER_USERNAME/reverseproxy

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/udagram-api-feed:v1
  - docker push $DOCKER_USERNAME/udagram-api-user:v1
  - docker push $DOCKER_USERNAME/udagram-frontend:latest
  - docker push $DOCKER_USERNAME/reverseproxy:latest