branches:
  only:
    - main
language: node_js
node_js:
  - 22

services:
  - docker

script:
## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
## Tagging
  - docker tag udagram-api-feed tinhtn/udagram-api-feed:latest
  - docker tag udagram-api-user tinhtn/udagram-api-user:latest
  - docker tag udagram-frontend tinhtn/udagram-frontend:latest
  - docker tag reverseproxy tinhtn/reverseproxy:latest
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
## Push
  - docker push tinhtn/udagram-api-feed
  - docker push tinhtn/udagram-api-user
  - docker push tinhtn/udagram-frontend
  - docker push tinhtn/reverseproxy